version: '3'
services:
  db:
    image: mysql:8.0.40
    container_name: mysql-db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=superSecretPassword
      - MYSQL_DATABASE=task
    volumes:
      - /home/sergioczp/Documents/todo-rest-api/db:/var/lib/mysql
